# Generated by Django 3.1.4 on 2020-12-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('Price', models.IntegerField(verbose_name='値段')),
                ('Explanation', models.TextField(max_length=200, verbose_name='商品説明')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Choices', models.CharField(choices=[('朝飯', '朝飯'), ('おかず', 'おかず'), ('主食', '主食'), ('おつまみ', 'おつまみ'), ('その他', 'その他')], max_length=10, verbose_name='カテゴリー')),
            ],
        ),
    ]
